version: '3'
services:
  db:
    image: mysql
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: users
      MYSQL_USER: vitor
      MYSQL_PASSWORD: secret
